<%@ Page Title="Gestion" Language="C#" MasterPageFile="~/Views/MasterPage/Master.Master" AutoEventWireup="true" CodeBehind="GestionBuzon.aspx.cs" Inherits="WebApplication1.Views.Admin.GestionBuzon" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <br />
    <h1>Gestor de Buzón y correos</h1>
    <br />
    <asp:GridView ID="GridView1" runat="server" CssClass="mGrid" AutoGenerateDeleteButton="True" AutoGenerateColumns="False" DataKeyNames="id" DataSourceID="SqlDataBuzon">
        <Columns>
            <asp:BoundField DataField="tipo" HeaderText="tipo" SortExpression="tipo" />
            <asp:BoundField DataField="sugerencia" HeaderText="sugerencia" SortExpression="sugerencia" />
            <asp:BoundField DataField="id" HeaderText="id" InsertVisible="False" ReadOnly="True" SortExpression="id" Visible="False" />
        </Columns>
    </asp:GridView>
    <asp:SqlDataSource ID="SqlDataBuzon" runat="server" 
        ConnectionString="<%$ ConnectionStrings:progWebConnectionString %>" 
        SelectCommand="SELECT * FROM [Sugerencias]"
        DeleteCommand="DELETE from [Sugerencias] where [id]=@id"
        ></asp:SqlDataSource>
    <asp:GridView ID="GridView2" runat="server" CssClass="mGrid" AutoGenerateDeleteButton="True" AutoGenerateColumns="False" DataSourceID="SqlDataCorreos">
        <Columns>
            <asp:BoundField DataField="email" HeaderText="email" SortExpression="email" />
        </Columns>
    </asp:GridView>
    <asp:SqlDataSource ID="SqlDataCorreos" runat="server" 
        ConnectionString="<%$ ConnectionStrings:progWebConnectionString %>" 
        SelectCommand="SELECT [email] FROM [Correos]"
        DeleteCommand="DELETE from [Correos] where [id]=@id"
        ></asp:SqlDataSource>
</asp:Content>
